### ISSUE TITLE
Custom mappings are read with the wrong encoding on Windows

### ISSUE THREAD

**Issue by DexLuther** [RickDB/PlexAniSync#100]
Tried to deal with the list of shows it spit out in the Failed list. After creating the custom mappings list, Plexanisync starts and then closes immediately. The only thing that is spit out in either logs (the normal or debug one) is this:

```
PlexAniSync - version: 1.3.16
[MAPPING] Custom map file found: custom_mappings.yaml
```

Not very helpful. Have no idea what the problem is.

Ran my custom mappings through a quick online YAML validator. Found a copy/paste error where one of the sections was missing a Seasons section. Fixed that, but still doesn't work. 

The only information I can find is in the pycache and having a look at the custom_mappings.cpython-39.pyc file in notpad++. The jumbled mess seems to say that the custom mapping file isn't valid. Doesn't say why though. Passing it through the online YAML validator says it's valid, so at least I know it's structured correctly now.

This is my custom_mappings.yaml file (updated):

```YAML
entries:
---
  - title: "Blue Exorcist"
    seasons:
      - season: 2
        anilist-id: 21861

  - title: "Dr. Stone"
    seasons:
      - season: 2
        anilist-id: 113936

  - title: "Full Metal Panic!"
    seasons:
      - season: 1
        anilist-id: 71
      - season: 2
        anilist-id: 72
      - season: 3
        anilist-id: 73
      - season: 4
        anilist-id: 21451

  - title: "Haganai: I Don't Have Many Friends"
    seasons:
      - season: 1
        anilist-id: 10719
      - season: 2
        anilist-id: 14967

  - title: "Heaven's Lost Property"
    seasons:
      - season: 1
        anilist-id: 5958
      - season: 2
        anilist-id: 8407

  - title: "High School DxD"
    seasons:
      - season: 1
        anilist-id: 11617
      - season: 2
        anilist-id: 15451
      - season: 3
        anilist-id: 20745
      - season: 4
        anilist-id: 97767 

  - title: "Is This A Zombie?"
    seasons:
      - season: 1
        anilist-id: 8841
      - season: 2
        anilist-id: 10790

  - title: Jormungand
    seasons:
      - season: 1
        anilist-id: 12413
      - season: 2
        anilist-id: 13331

  - title: "Love, Chunibyo & Other Delusions!"
    synonyms:
      - "Chuunibyou demo Koi ga Shitai!"
      - "Chūnibyō demo Koi ga Shitai!"
    seasons:
      - season: 1
        anilist-id: 14741
      - season: 2
        anilist-id: 18671

  - title: "Miss Kobayashi's Dragon Maid"
    synonyms:
      - "Kobayashi-san Chi no Maidragon"
    seasons:
      - season: 1
        anilist-id: 21776
      - season: 2
        anilist-id: 107717

  - title: "My Teen Romantic Comedy SNAFU"
    synonyms:
      - "Yahari Ore no Seishun Love Come wa Machigatteiru."
    seasons:
      - season: 1
        anilist-id: 14813
      - season: 2
        anilist-id: 20698
      - season: 3
        anilist-id: 108489

  - title: Noragami
    seasons:
      - season: 1
        anilist-id: 20447
      - season: 2
        anilist-id: 21128

  - title: "Queen's Blade"
    seasons:
      - season: 1
        anilist-id: 4719
      - season: 2
        anilist-id: 6633

  - title: "Rosario + Vampire"
    seasons:
      - season: 1
        anilist-id: 2993
      - season: 2
        anilist-id: 4214

  - title: "School Rumble"
    seasons:
      - season: 1
        anilist-id: 24
      - season: 2
        anilist-id: 846

  - title: "The Testament of Sister New Devil"
    seasons:
      - season: 1
        anilist-id: 20678
      - season: 2
        anilist-id: 21110

  - title: "To Love-Ru"
    seasons:
      - season: 1
        anilist-id: 3455
      - season: 2
        anilist-id: 9181
      - season: 3
        anilist-id: 13663
      - season: 4
        anilist-id: 20995

  - title: VanDread
    seasons:
      - season: 1
        anilist-id: 180
      - season: 2
        anilist-id: 181

  - title: 'Yamada-kun and the Seven Witches (2015)'
    synonyms:
      - "Yamada-kun and the Seven Witches"
      - "Yamada-kun to 7-nin no Majo"
    seasons:
      - season: 1
        anilist-id: 20966

  - title: "Saekano: How to Raise a Boring Girlfriend"
    seasons:
      - season: 1
        anilist-id: 20657
      - season: 2
        anilist-id: 21180

  - title: "Is It Wrong to Try to Pick Up Girls in a Dungeon?"
    synonyms:
      - "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka"
    seasons:
      - season: 1
        anilist-id: 20920
      - season: 2
        anilist-id: 101167
      - season: 3
        anilist-id: 112124
      - season: 4
        anilist-id: 129196
```

**Comment by KaiserBh** [comment]
> Tried to deal with the list of shows it spit out in the Failed list. After creating the custom mappings list, Plexanisync starts and then closes immediately. The only thing that is spit out in either logs (the normal or debug one) is this:
> 
> ```
> PlexAniSync - version: 1.3.16
> [MAPPING] Custom map file found: custom_mappings.yaml
> ```
> 
> Not very helpful. Have no idea what the problem is.
> 
> Ran my custom mappings through a quick online YAML validator. Found a copy/paste error where one of the sections was missing a Seasons section. Fixed that, but still doesn't work.
> 
> The only information I can find is in the pycache and having a look at the custom_mappings.cpython-39.pyc file in notpad++. The jumbled mess seems to say that the custom mapping file isn't valid. Doesn't say why though. Passing it through the online YAML validator says it's valid, so at least I know it's structured correctly now.
> 
> This is my custom_mappings.yaml file (updated):
> 
> ```yaml
> entries:
> ---
>   - title: "Blue Exorcist"
>     seasons:
>       - season: 2
>         anilist-id: 21861
> 
>   - title: "Dr. Stone"
>     seasons:
>       - season: 2
>         anilist-id: 113936
> 
>   - title: "Full Metal Panic!"
>     seasons:
>       - season: 1
>         anilist-id: 71
>       - season: 2
>         anilist-id: 72
>       - season: 3
>         anilist-id: 73
>       - season: 4
>         anilist-id: 21451
> 
>   - title: "Haganai: I Don't Have Many Friends"
>     seasons:
>       - season: 1
>         anilist-id: 10719
>       - season: 2
>         anilist-id: 14967
> 
>   - title: "Heaven's Lost Property"
>     seasons:
>       - season: 1
>         anilist-id: 5958
>       - season: 2
>         anilist-id: 8407
> 
>   - title: "High School DxD"
>     seasons:
>       - season: 1
>         anilist-id: 11617
>       - season: 2
>         anilist-id: 15451
>       - season: 3
>         anilist-id: 20745
>       - season: 4
>         anilist-id: 97767 
> 
>   - title: "Is This A Zombie?"
>     seasons:
>       - season: 1
>         anilist-id: 8841
>       - season: 2
>         anilist-id: 10790
> 
>   - title: Jormungand
>     seasons:
>       - season: 1
>         anilist-id: 12413
>       - season: 2
>         anilist-id: 13331
> 
>   - title: "Love, Chunibyo & Other Delusions!"
>     synonyms:
>       - "Chuunibyou demo Koi ga Shitai!"
>       - "Chūnibyō demo Koi ga Shitai!"
>     seasons:
>       - season: 1
>         anilist-id: 14741
>       - season: 2
>         anilist-id: 18671
> 
>   - title: "Miss Kobayashi's Dragon Maid"
>     synonyms:
>       - "Kobayashi-san Chi no Maidragon"
>     seasons:
>       - season: 1
>         anilist-id: 21776
>       - season: 2
>         anilist-id: 107717
> 
>   - title: "My Teen Romantic Comedy SNAFU"
>     synonyms:
>       - "Yahari Ore no Seishun Love Come wa Machigatteiru."
>     seasons:
>       - season: 1
>         anilist-id: 14813
>       - season: 2
>         anilist-id: 20698
>       - season: 3
>         anilist-id: 108489
> 
>   - title: Noragami
>     seasons:
>       - season: 1
>         anilist-id: 20447
>       - season: 2
>         anilist-id: 21128
> 
>   - title: "Queen's Blade"
>     seasons:
>       - season: 1
>         anilist-id: 4719
>       - season: 2
>         anilist-id: 6633
> 
>   - title: "Rosario + Vampire"
>     seasons:
>       - season: 1
>         anilist-id: 2993
>       - season: 2
>         anilist-id: 4214
> 
>   - title: "School Rumble"
>     seasons:
>       - season: 1
>         anilist-id: 24
>       - season: 2
>         anilist-id: 846
> 
>   - title: "The Testament of Sister New Devil"
>     seasons:
>       - season: 1
>         anilist-id: 20678
>       - season: 2
>         anilist-id: 21110
> 
>   - title: "To Love-Ru"
>     seasons:
>       - season: 1
>         anilist-id: 3455
>       - season: 2
>         anilist-id: 9181
>       - season: 3
>         anilist-id: 13663
>       - season: 4
>         anilist-id: 20995
> 
>   - title: VanDread
>     seasons:
>       - season: 1
>         anilist-id: 180
>       - season: 2
>         anilist-id: 181
> 
>   - title: 'Yamada-kun and the Seven Witches (2015)'
>     synonyms:
>       - "Yamada-kun and the Seven Witches"
>       - "Yamada-kun to 7-nin no Majo"
>     seasons:
>       - season: 1
>         anilist-id: 20966
> 
>   - title: "Saekano: How to Raise a Boring Girlfriend"
>     seasons:
>       - season: 1
>         anilist-id: 20657
>       - season: 2
>         anilist-id: 21180
> 
>   - title: "Is It Wrong to Try to Pick Up Girls in a Dungeon?"
>     synonyms:
>       - "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka"
>     seasons:
>       - season: 1
>         anilist-id: 20920
>       - season: 2
>         anilist-id: 101167
>       - season: 3
>         anilist-id: 112124
>       - season: 4
>         anilist-id: 129196
> ```

Hmm could be encoding, but for easy test would be download this https://github.com/RickDB/PlexAniSync-Custom-Mappings/blob/main/series-tvdb.en.yaml and use it as the custom mapping for now. If it run successfully then try editing it and put the values you have.

**Comment by DexLuther** [comment]
> Hmm could be encoding, but for easy test would be download this https://github.com/RickDB/PlexAniSync-Custom-Mappings/blob/main/series-tvdb.en.yaml and use it as the custom mapping for now. If it run successfully then try editing it and put the values you have.

Tried this, but the same thing happens. Opens then closes immediately. Log file shows nothing other than the version and that the custom mapping was found/loaded.

The most information seems to come from the _Pycache_ Custom mapping file:

`a

    !tçaL  ã                   @   sp   d dl Z d dlZd dlZd dlmZ d dlmZ d dlZd dlm	Z	 e 
d¡ZdZeG dd„ dƒƒZ
d	d
„ ZdS )é    N)ÚList)Ú	dataclass)ÚYamaleErrorÚPlexAniSyncz;C:\Python39\Scripts\PlexAniSync-1.3.16\custom_mappings.yamlc                   @   s&   e Zd ZU eed< eed< eed< dS )ÚAnilistCustomMappingÚseasonZanime_idÚstartN)Ú__name__Ú
__module__Ú__qualname__ÚintÚ__annotations__© r   r   ú9C:\Python39\Scripts\PlexAniSync-1.3.16\custom_mappings.pyr      s   
r   c                  C   sz  i } t j t¡s$t dt› ¡ nRt dt› ¡ tjddd}tjtdd}zt 	||¡ W n` t
yÀ } zHt d¡ |jD ] }|j
D ]}t |› d¡ qŠq€t d¡ W Y d }~n
d }~0 0 |d	 d	 d
 D ]¢}t|d ƒ}| dg ¡}g }	|d
 D ]T}
|
d }|
d }|
 dd¡}
t d|› d|› d|› d|
› ¡ |	 t|||
ƒ¡ qú|	| | ¡ < |D ]}|	| | ¡ < q`qÒ| S )Nz%[MAPPING] Custom map file not found: z![MAPPING] Custom map file found: z./custom_mappings_schema.yamlÚruamel)Úparserz#Custom Mappings validation failed!
Ú
é   r   ÚentriesÚtitleÚsynonymsZseasonsr   z
anilist-idr   z)[MAPPING] Adding custom mapping | title: z | season: z | anilist id: z
 | start: )ÚosÚpathÚisfileÚMAPPING_FILEÚloggerÚinfoÚyamaleZmake_schemaZ	make_dataÚvalidater   ÚerrorÚresultsÚerrorsÚsysÚexitÚstrÚgetÚappendr   Úlower)Úcustom_mappingsZschemaZ
file_mappingsÚeÚresultr   Z
file_entryZseries_titler   Zseries_mappingsZfile_seasonr   Z
anilist_idr   Zsynonymr   r   r   Úread_custom_mappings   s<    


 ÿr+   )r   Úloggingr"   Útypingr   Zdataclassesr   r   Zyamale.yamale_errorr   Ú	getLoggerr   r   r   r+   r   r   r   r   Ú<module>   s   
`

Seems almost corrupted, but that's no surprise. On line 20 it says "Not Validated" and shows it's being checked against the shema.

I don't know why it would be different, and when comparing it between everything, I don't see where the problem would be. I'll include it here just to be sure:

```YAML
entries: list(include('entry'), min=1)
---
entry:
  title: str()
  synonyms: list(str(), required=False)
  seasons: list(include('season'), min=1)

season:
  season: int(min=1)
  anilist-id: int(min=1)
  start: int(required=False)
```
