### ISSUE TITLE
Add the ability to track multi-part episodes with custom_mappings

### ISSUE THREAD

**Issue by cantnamethis** [RickDB/PlexAniSync#110]
Currently it's not possible to track multi-episode anime with the script, because either Anilist or TVDB would have either too many or too few episodes respectively, a fix would be adding "multiplier" and "divider" variables to the season entries.

Example for Panty & Stocking with Garterbelt where there are 26 episodes on TVDB but only 13 on Anilist
```
entries:
  - title: "Panty & Stocking with Garterbelt"
    seasons:
      - season: 1
        anilist-id: 8795
        divider: 2
```
This would update Anilist once for every 2 episodes watched on Plex, the same could be done in reverse with the multiplier option,
an example with The Disastrous Life of Saiki K. where there are 120 on Anilist, but only 25 on TVDB
```
entries:
  - title: "The Disastrous Life of Saiki K."
    seasons:
      - season: 1
        anilist-id: 21804
        multiplier: 5
```
Now when 1 episode is watched on Plex, the script updates 5 on Anilist.
