### ISSUE TITLE
Add entry ID into schema

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#193]
For example, allow tmdb/tvdb id into schema
Like `tmdb-id: 123` or `tvdv-id: 123`

Maybe even allow imdb just for the sake of completion

At least, while I'm editing entries, it's super helpful having IDs visible so I can quickly go to the series page, without having to manually search it.

Two examples

Either,
A) Only have for example `tvdb-id` on TVDB mappings
B) Have `tvdb-id`, and `tmdb-id` on all mapping, so it can be filled for completion

```
entries:
  - title: "86: Eighty Six"
    tmdb-id: 100565
    synonyms:
      - "Eighty Six"	
```

**Comment by reconman** [comment]
I'd rather suggest leaving the full URLs as comments in the yaml.

So, for example:
```yaml
entries:
  - title: "86: Eighty Six"
    # https://www.themoviedb.org/tv/100565-86
    # https://thetvdb.com/series/eighty-six
    synonyms:
      - "Eighty Six"
```
