### ISSUE TITLE
One Piece does not work anymore with TMDB

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#212]
Discussed with @Jaynator495 and @reconman in April on the Discord

Might have broken in #174 
1.3.21 works, 1.3.22 and later doesn't work

This is with TheMovieDB due to their absolute numbers while keeping season format

I noticed this again yesterday when I watched One Piece and it updated to episode 9600 or something

![image](https://github.com/RickDB/PlexAniSync/assets/10836780/b2e2612e-ce01-4843-8165-6155a5a16a07)

**Comment by buthed010203** [comment]
A bit of a hack but maybe there could be an optional boolean added to the mapping schema that could toggle between the current logic of summing the watch counts of seasons mapped to the same AL id (when no mapped_start is specified) and simply taking the max watched episode id. https://github.com/RickDB/PlexAniSync/blob/a8df9cbb122494be556fdd0a29ad718b437358ff/plexanisync/anilist.py#L93-L96

**Comment by rcdailey** [comment]
I'd like to share that I also had trouble with One Piece. here's the logs:

```
[PLEX] Retrieving anime series from section: Anime Series
[PLEX] Found 361 anime series in section: Anime Series
[PLEX] Found matching anime series
[PLEX] Retrieving watch count for series
[PLEX] 118 episodes watched for One Piece season 17
[PLEX] 33 episodes watched for One Piece season 18
[PLEX] 98 episodes watched for One Piece season 19
[PLEX] 14 episodes watched for One Piece season 20
[PLEX] 191 episodes watched for One Piece season 21
[PLEX] Found 1 watched series
[ANILIST] Matching Plex series to Anilist
[ANILIST] --------------------------------------------------
[ANILIST] Failed to find valid season title match on AniList for: One Piece season 17
[ANILIST] Failed to find valid season title match on AniList for: One Piece season 18
[ANILIST] Failed to find valid season title match on AniList for: One Piece season 19
[ANILIST] Failed to find valid season title match on AniList for: One Piece season 20
[ANILIST] Failed to find valid season title match on AniList for: One Piece season 21
```

**Comment by Ninelpienel** [comment]
Still no proper solution to the problem?

**Comment by reconman** [comment]
I patched PlexAniSync so TMDB One Piece works with a mapping like this:
```
  - title: "One Piece"
    seasons:
      - season: 1
        anilist-id: 21
      - season: 2
        anilist-id: 21
      - season: 3
        anilist-id: 21
      - season: 4
        anilist-id: 21
      - season: 5
        anilist-id: 21
      - season: 6
        anilist-id: 21
      - season: 7
        anilist-id: 21
      - season: 8
        anilist-id: 21
      - season: 9
        anilist-id: 21
      - season: 10
        anilist-id: 21
      - season: 11
        anilist-id: 21
      - season: 12
        anilist-id: 21
      - season: 13
        anilist-id: 21
      - season: 14
        anilist-id: 21
      - season: 15
        anilist-id: 21
      - season: 16
        anilist-id: 21
      - season: 17
        anilist-id: 21
      - season: 18
        anilist-id: 21
      - season: 19
        anilist-id: 21
      - season: 20
        anilist-id: 21
      - season: 21
        anilist-id: 21
      - season: 22
        anilist-id: 21
```
