### ISSUE TITLE
Failed to find valid season title match (HxH 1999)

### ISSUE THREAD

**Issue by bl4ckswordsman** [RickDB/PlexAniSync#273]
Is there any workaround for titles that have have a separate and differently named entry in anilist, but that in Plex/tvdb are seasons of a another main title?

For instance, with Hunter x Hunter (1999), I get this error:

```
[ANILIST] Failed to find valid season title match on AniList for: Hunter × Hunter season 2
```
The first season syncs correctly, but not the second one since in Anilist the second season is called "Hunter × Hunter OVA".

I've tried altering the custom mapping with synonyms etc, no luck.

```
  - title: "Hunter x Hunter"
    seasons:
      - season: 1
        anilist-id: 136
      - season: 2
        anilist-id: 137
      - season: 3
        anilist-id: 138
      - season: 4
        anilist-id: 139
        
```

**Comment by Soitora** [comment]
What agent are you using on Plex?
Can you also show a screenshot of your Plex item, including season overview?

**Comment by bl4ckswordsman** [comment]
> What agent are you using on Plex?
> Can you also show a screenshot of your Plex item, including season overview?

I recently switched from the HamaTV agent to the latest Plex Series one. I'm not sure but it might've worked before with the HamaTV agent.

Here's a screenshot of the item:

![Screenshot_20240828-175507.png](https://github.com/user-attachments/assets/ac8c68c8-6f51-4906-8255-0a274ec0f5ca)

**Comment by Soitora** [comment]
For one, I can see that your "x" is different from what Plex has printed.
If you copy the Plex title, does it work now?

If you want to enforce a match, try adding a guid, like the example below:

```yml
  - title: "Hunter × Hunter"
    guid: plex://show/5d9c090246115600200ae731
    seasons:
      - season: 1
        anilist-id: 136
      - season: 2
        anilist-id: 137
      - season: 3
        anilist-id: 138
      - season: 4
        anilist-id: 139
```

I have a program to assist with creating mappings: [PlexAniSync-Mapping-Assistant](https://github.com/Soitora/PlexAniSync-Mapping-Assistant/)
And I also have a userscript for grabbing the guid directly inside of plex: [Plex GUID Grabber](https://gist.github.com/Soitora/26eebf4cf388dc496eca4b29a227973b)

If neither of these work, you can join the [PlexAniSync Discord server](https://discord.gg/a9cu5t5fKc) for live help.
