### ISSUE TITLE
Mapping for split seasons

### ISSUE THREAD

**Issue by reconman** [RickDB/PlexAniSync#43]
Re:Zero's TVDB entry has 2 seasons listed. Season 2 has 2 associated Anilist entries, https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/ and https://anilist.co/anime/119661/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season-Part-2/.

This also affects Space Dandy and Yuukoku no Moriarty.

Any ideas on how this could be solved?

**Comment by KaiserBh** [comment]
> Re:Zero's TVDB entry has 2 seasons listed. Season 2 has 2 associated Anilist entries, https://anilist.co/anime/108632/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season/ and https://anilist.co/anime/119661/ReZero-kara-Hajimeru-Isekai-Seikatsu-2nd-Season-Part-2/.
> 
> This also affects Space Dandy and Yuukoku no Moriarty.
> 
> Any ideas on how this could be solved?

Are you using TVDB as the metadata agent?

**Comment by reconman** [comment]
Hama, but based on TVDB.

**Comment by KaiserBh** [comment]
> 
> 
> Hama, but based on TVDB.
> 
> I need TVDB for Sonarr/pymedusa.

ouhh yea I know what you mean now, tbf I think you need to split it yourself , as of now haven't found a solution myself.

**Comment by sshawnsamuell** [comment]
It looks like it works if you only have Part 2 in your custom mapping for S2.

**Comment by reconman** [comment]
But how does it map episode 14 to 1 then? Magic?

**Comment by sshawnsamuell** [comment]
Never mind, it looked like it had worked at first, but looking at it now my anilist has s2pt2 at episode 16/12.

**Comment by Soitora** [comment]
Maybe something like they did on https://github.com/Anime-Lists/anime-lists/ with episode offsets or something

**Comment by reconman** [comment]
If I could decide on my own, I would change the custom_mapping to YAML format and then add optional start and end parameters. So entries would look like this:

```yaml
mappings:
  - title: The Rising of the Shield Hero
    season: 1
    anilist-id: 99263
  - title: Re:ZERO -Starting Life in Another World-
    season: 2
    anilist-id: 108632
    start: 1
    end: 13
  - title: Re:ZERO -Starting Life in Another World-
    season: 2
    anilist-id: 119661
    start: 14
    end: 25
```
