### ISSUE TITLE
Missing previous season causes issues matching

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#61]
Maybe I missed some other issue about it but here how's it is for me:

I use TheTVDB matching for **One Piece**, due to the sheer size of the series I only have **Season 21**, which start at episode 892.
Now, I can't really find a possible way to tell the tool that season 21 starts at absolute number 892 or something similiar.

Know any possible fix without having to add dummy files? Or is it possible to add to the mapping a `start-absolute` field or something?

**Comment by reconman** [comment]
What happens if you use this custom mapping?

```
  - title: One Piece
    seasons:
      - season: 21
        anilist-id: 21
        start: -891
```

I have no idea what will happen, but it can't hurt trying.
