### ISSUE TITLE
Allow mapping synonyms

### ISSUE THREAD

**Issue by Soitora** [RickDB/PlexAniSync#82]
Hey again

As the title suggests, something like:
```yaml
  - title: "Demon Slayer: Kimetsu no Yaiba"
    seasons:
      - season: 1
        anilist-id: 101922
      - season: 2
        anilist-id: 129874
    synonyms:
      - title: "Demon Slayer"
      - title: "Kimetsu no Yaiba"

  - title: "Fruits Basket"
    seasons:
      - season: 1
        anilist-id: 105334
      - season: 2
        anilist-id: 111762
      - season: 3
        anilist-id: 124194
    synonyms:
      - title: "Fruits Basket (2019)"
```

Would allow the final flexibility needed to do an ultimate mapping.
If it failed the main title match it could go on and check each synonym at a time and stopping if match found.
Example of issue: https://github.com/mizz141/PlexAniSync-Mappings/issues/14
